name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 안드로이드 빌드
      - name: "Build Android project"
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew assembleDebug"
        env:
          TEST_STORE_PW: ${{ secrets.TEST_STORE_PW }}
          TEST_KEY_ALIAS: ${{ secrets.TEST_KEY_ALIAS }}
          TEST_KEY_PW: ${{ secrets.TEST_KEY_PW }}
          run: echo ${{ secrets.TEST_DEBUG_KEY }} > ../cyn_debug_key.jks

      # 환경변수 가져오기 테스트
      - name: Load local env vars
        run: |
          echo test_key_alias : ${{ env.TEST_KEY_ALIAS }}
          echo test_key_pw : ${{ env.TEST_KEY_PW }}

      # 깃헙 시크릿 가져오기 테스트
      - name: Load Github secret value
        run: echo test secret ${{ secrets.TEST_SECRET_KEY }}
