name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
        
  setup-android:
    - name: setup-android
    - uses: msfjarvis/setup-android@0.2
    - with:
        # Gradle tasks to run - If you want to run ./gradlew assemble, specify assemble here. 
        gradleTasks: # optional, d
