name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 키 세팅
      - name: "Key setting"
        env:
          TEST_STORE_PW: ${{ secrets.TEST_STORE_PW }}
          TEST_KEY_ALIAS: ${{ secrets.TEST_KEY_ALIAS }}
          TEST_KEY_PW: ${{ secrets.TEST_KEY_PW }}
          DEBUG_KEY: ${{ secrets.TEST_DEBUG_KEY }}
        run: |
          echo first_key_check---$DEBUG_KEY
          echo $DEBUG_KEY | base64 --decode
          echo second_key_check---$DEBUG_KEY
          echo $DEBUG_KEY > ../cyn_debug_key.jks
          echo decrypted_file--- ${../cyn_debug_key.jks}

      # 안드로이드 빌드
      - name: "Build Android project"
        with:
          args: "./gradlew assembleDebug"
        uses: vgaidarji/android-github-actions-build@v1.0.1

#      # 환경변수 가져오기 테스트
#      - name: Load local env vars
#        run: |
#          echo test_key_alias : ${{ env.TEST_KEY_ALIAS }}
#          echo test_key_pw : ${{ env.TEST_KEY_PW }}

#      # 깃헙 시크릿 가져오기 테스트
#      - name: Load Github secret value
#        run: echo test secret ${{ secrets.TEST_SECRET_KEY }}
