name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      env:
        test_secret: ${{ secret.TEST_SECRET_KEY }}


      - uses: actions/checkout@v2
      # 자바 버전 설정
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # 유닛 테스트
      - name: Unit test 한글 되나 테스트
        run: bash ./gradlew test --stacktrace

      # 깃헙 환경변수 가져오기 테스트
      - name: Load Github secret value
        run: |
          echo home : ${{ env.HOME }}
          echo github_repo : ${{ env.GITHUB_REPOSITORY }}

      # 깃헙 시크릿 가져오기 테스트
      - name: Load Github secret value
        run: echo $test_secret
